services:
  mongodb:
    image: mongo:6.0
    container_name: sgm_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    volumes:
      - mongo_data:/data/db
  
  
  mongo-express:
    image: mongo-express
    container_name: sgm_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "rootpassword"
      ME_CONFIG_MONGODB_SERVER: "mongodb"

volumes:
  mongo_data: